**Word Embedding Technniques using Enbedding layer in Keras**

In [1]:
# Libraries Used: Keras, TensorFlow

In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [5]:
#sentences
sent= ['the glass of milk',
      'the glass of juice',
      'the cup of tea',
      'i am a good boy',
      'I am a good developer',
      'understand the meaning of words',
      'your videos are good']
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'i am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
voc_size=10000  #size of the dictionary

**One Hot Representation**

In [7]:
onehot_repr = [one_hot(words, voc_size) for words in sent]
print(onehot_repr)  #index from the dictionary

[[7268, 6028, 6218, 6206], [7268, 6028, 6218, 662], [7268, 5150, 6218, 4205], [6806, 5933, 8074, 4635, 9361], [6806, 5933, 8074, 4635, 2841], [8687, 7268, 5410, 6218, 659], [8282, 2542, 6380, 4635]]


**Word Embedding Representation**

In [9]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [11]:
sent_length = 8
embedded_docs = pad_sequences(onehot_repr, padding = 'pre', maxlen = sent_length)
# 'pre' it will add zeros in front of sentences to make it equal

In [12]:
print(embedded_docs)

[[   0    0    0    0 7268 6028 6218 6206]
 [   0    0    0    0 7268 6028 6218  662]
 [   0    0    0    0 7268 5150 6218 4205]
 [   0    0    0 6806 5933 8074 4635 9361]
 [   0    0    0 6806 5933 8074 4635 2841]
 [   0    0    0 8687 7268 5410 6218  659]
 [   0    0    0    0 8282 2542 6380 4635]]


In [13]:
dim = 10  #features

In [14]:
model = Sequential()
model.add(Embedding(voc_size, 10, input_length = sent_length))
model.compile('adam', 'mse')

In [15]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [16]:
#in order to see how my senteces will converted into vectors
print(model.predict(embedded_docs))

[[[ 0.01269004  0.0319656  -0.03940643  0.04900597  0.04138208
    0.03342212  0.02691184  0.03933573  0.03178427  0.02849158]
  [ 0.01269004  0.0319656  -0.03940643  0.04900597  0.04138208
    0.03342212  0.02691184  0.03933573  0.03178427  0.02849158]
  [ 0.01269004  0.0319656  -0.03940643  0.04900597  0.04138208
    0.03342212  0.02691184  0.03933573  0.03178427  0.02849158]
  [ 0.01269004  0.0319656  -0.03940643  0.04900597  0.04138208
    0.03342212  0.02691184  0.03933573  0.03178427  0.02849158]
  [-0.00090203 -0.00187648  0.03641266 -0.00043428 -0.00460634
    0.03864473 -0.00042569 -0.03248756 -0.00596387  0.02540375]
  [-0.00194665 -0.03780263  0.02117002 -0.04589639 -0.00442351
   -0.03643352 -0.03366785 -0.00051299 -0.03699492 -0.00786345]
  [-0.00594796 -0.01938713 -0.01456482  0.01219506  0.01953158
   -0.03166174  0.02978224  0.03262581  0.01440061  0.01896608]
  [-0.01207256 -0.00383761  0.00799538  0.00944575  0.02517194
    0.02426391  0.01741632  0.03980077 -0.032193

In [17]:
embedded_docs[0]

array([   0,    0,    0,    0, 7268, 6028, 6218, 6206])

In [18]:
#first sentence representation into vectors
print(model.predict(embedded_docs)[0])

[[ 0.01269004  0.0319656  -0.03940643  0.04900597  0.04138208  0.03342212
   0.02691184  0.03933573  0.03178427  0.02849158]
 [ 0.01269004  0.0319656  -0.03940643  0.04900597  0.04138208  0.03342212
   0.02691184  0.03933573  0.03178427  0.02849158]
 [ 0.01269004  0.0319656  -0.03940643  0.04900597  0.04138208  0.03342212
   0.02691184  0.03933573  0.03178427  0.02849158]
 [ 0.01269004  0.0319656  -0.03940643  0.04900597  0.04138208  0.03342212
   0.02691184  0.03933573  0.03178427  0.02849158]
 [-0.00090203 -0.00187648  0.03641266 -0.00043428 -0.00460634  0.03864473
  -0.00042569 -0.03248756 -0.00596387  0.02540375]
 [-0.00194665 -0.03780263  0.02117002 -0.04589639 -0.00442351 -0.03643352
  -0.03366785 -0.00051299 -0.03699492 -0.00786345]
 [-0.00594796 -0.01938713 -0.01456482  0.01219506  0.01953158 -0.03166174
   0.02978224  0.03262581  0.01440061  0.01896608]
 [-0.01207256 -0.00383761  0.00799538  0.00944575  0.02517194  0.02426391
   0.01741632  0.03980077 -0.03219386 -0.0368243 ]]